### ISSUE TITLE
Anos nas datas de filiação e desfiliação estão errados

### ISSUE THREAD

**Issue by gabriel19913** [turicas/eleicoes-brasil#10]
O ano nas datas de filiação e desfiliação estão estão errados conforme print abaixo.
<img src="https://i.ibb.co/7bFhmKB/data-filiacao.png">

**Comment by turicas** [comment]
Esse é um erro nos dados originais. Essas colunas não estão sendo convertidas pelo script (justamente por apresentarem dados inconsistentes e não ser tão simples fazer essa conversão, dado que qualquer alteração que façamos pode introduzir dados incorretos).
O que talvez possamos fazer é converter do formato "<dia> de <mês> de <ano>" para o formato mais padronizado "YYYY-MM-DD" e, após filtrar por datas menores que 1900 e maiores que 2020, podemos fazer um pedido de acesso à informação pedindo a correção dos dados.

**Comment by turicas** [comment]
Fechando essa pois já existe a #2.
