### ISSUE TITLE
PermissionError: [WinError 32] O arquivo já está sendo usado por outro processo:

### ISSUE THREAD

**Issue by evertoncbx** [turicas/eleicoes-brasil#22]
Quando tento executar o código ele apresenta o seguinte erro:

Traceback (most recent call last):
  File "tse.py", line 209, in <module>
    extract_data(
  File "tse.py", line 41, in extract_data
    result = extractor.download(year, force=force_redownload)
  File "D:\dataScience\perfil_Parlamentar\eleicoes-brasil-master\extractors.py", line 238, in download
    file_data = download_file(url, progress=True, chunk_size=256 * 1024)
  File "D:\dataScience\anaconda\lib\site-packages\rows\utils\__init__.py", line 473, in download_file
    os.rename(tmp.name, filename)
PermissionError: [WinError 32] O arquivo já está sendo usado por outro processo: 'C:\\Users\\Everton\\AppData\\Local\\Temp\\tmp3dqrttyw' -> 'C:\\Users\\Everton\\AppData\\Local\\Temp\\tmp3dqrttyw.zip'

Aparentemente é um erro referente a abertura do arquivo zip, parece que por ele não ser fechado acaba gerando essa exception

Já tentei fazer de várias formas mas não sei o que está errado no código ou sou eu que estou fazendo errado?

**Comment by turicas** [comment]
Você abriu o arquivo ZIP em seu computador usando outro software?

**Comment by evertoncbx** [comment]
tentei debugar no spyder, aparentemente ocorre no comando downloa_file, tentei provocar o erro:

> url = 'https://www.tse.jus.br/hotsites/pesquisas-eleitorais/candidatos_anos/2020.html'
>         
>         file_data = download_file(url, progress=True, chunk_size=256 * 1024)
>         Downloading file: 7.54kbytes [00:00, 987kbytes/s]
>         Traceback (most recent call last):
>         
>           File "<ipython-input-7-af2285908fa8>", line 1, in <module>
>             file_data = download_file(url, progress=True, chunk_size=256 * 1024)
>         
>           File "D:\dataScience\anaconda\lib\site-packages\rows\utils\__init__.py", line 473, in download_file
>             os.rename(tmp.name, filename)
>         
>         PermissionError: [WinError 32] O arquivo já está sendo usado por outro processo: 'C:\\Users\\Everton\\AppData\\Local\\Temp\\tmpxcviv87a' -> 'C:\\Users\\Everton\\AppData\\Local\\Temp\\tmpxcviv87a.html'
> 


Não tinha nenhuma outra janela aberta no windows 10, e verificando esse arquivo no gerenciador de tarefas ele esta sendo usado pelo próprio python

**Comment by evertoncbx** [comment]
Aparentemente precisa fechar a variável "tmp", aberto na linha 427, acrescentei o comand  tmp.close() na linha 468, no arquivo __init__.py do pacote instalado em ...\rows\utils 
O código seguiu normalmente, ainda estou fazendo mais testes para verificar se era isso mesmo
